### ISSUE TITLE
Use mitochondria genome only or use all chromosomes

### ISSUE THREAD

**Issue by Puriney** [caleblareau/mgatk#23]
Hello Caleb, 
I was wondering if `mgatk` will only recognize mitochondria reads even if I give BAM containing all chromosomes.

For example,  I am running mgatk on a 10x scATAC data of mm10. 

**Step-1**. Having created a custom reference, do I let cellranger align reads to all chromosomes? 

1.1. ✅ Mask the mt black region.
```
bedtools maskfasta -fi old_mm10.fa -bed mito_blacklist.bed  -fo new_mm10.fa
```

1.2 Excute `cellranger-atac mkref` as the 10x [instruction](https://support.10xgenomics.com/single-cell-atac/software/pipelines/latest/advanced/references). Here, should I include the 'chrM' in the `PRIMARY_ASSEMBLY` for `mkref` so that the `cellranger-atac count` will align reads to all chromosomes including chrM? Or should I simply type 'chrM' only for `PRIMARY_ASSEMBLY` so that the resulted BAM only contain chrM reads?

**Step-2**. Run `mgatk`. How should I set the `--mito-genome` parameter? Should I simply claim 'mm10' or should I feed the FASTA file? Which FASTA file? Should it include all chromosomes or chrM only?

Many thanks.

Currently, I let cellranger align reads to all chromosomes so that the BAM contains all chromosomes. Then I claim mm10 in the `--mito-genome` parameter when running `mgatk`.

**Comment by caleblareau** [comment]
1) Yes— the idea is that you should still retain the full functionality of CellRanger-ATAC, so leave the nuclear chromosomes the same (aka don’t only use chromosome M)
2) Many reference genomes are already supported (mm10 is supported). You can optionally supply the fasta file of only the mitochondrial chromsomsome used in the alignment if the reference genome doesn’t match what is supported (see `mgatk support` for a list of such genomes)

On Aug 25, 2020, at 8:41 PM, Yun YAN <notifications@github.com<mailto:notifications@github.com>> wrote:



Hello Caleb,
I was wondering should I use mitochondria only or all chromosomes?

For example, I am running mgatk on a 10x scATAC data of mm10.

Step-1. Having created a custom reference, do I let cellranger align reads to all chromosomes?

1.1. ✅ Mask the mt black region.

bedtools maskfasta -fi old_mm10.fa -bed mito_blacklist.bed  -fo new_mm10.fa


1.2 Excute cellranger-atac mkref as the 10x instruction<https://support.10xgenomics.com/single-cell-atac/software/pipelines/latest/advanced/references>. Here, should I include the 'chrM' in the PRIMARY_ASSEMBLY for mkref so that the cellranger-atac count will align reads to all chromosomes including chrM? Or should I simply type 'chrM' only for PRIMARY_ASSEMBLY so that the resulted BAM only contain chrM reads?

Step-2. Run mgatk. How should I set the --mito-genome parameter? Should I simply claim 'mm10' or should I feed the FASTA file? Which FASTA file? Should it include all chromosomes or chrM only?

Many thanks.

Currently, I let cellranger align reads to all chromosomes so that the BAM contains all chromosomes. Then I claim mm10 in the --mito-genome parameter when running mgatk.

**Comment by Puriney** [comment]
I see. Thank you very much.
