### ISSUE TITLE
Using scRNA

### ISSUE THREAD

**Issue by PasLukas** [caleblareau/mgatk#25]
Hey Caleb,

I am currently working on scATAC data but was wondering if it were possible to use mgatk with scRNA data.
Do you know how to implement scRNA into the mgatk workflow or which prerequisites are needed to work with scRNA.
As I am aware the calling of SNV does not seem to be working. Is it possible to circumvent this problem by providing a list of SNV coming from scATAC data?  

Thanks and greetings.

**Comment by caleblareau** [comment]
So it's definitely already possible. In principle, you can run the CLI to get per position / per genotype counts (if you have 10x data, I discuss how to deal with the UMI here: https://github.com/caleblareau/mgatk/wiki/Process-mtDNA-from-CellRanger-ATAC). Once you have these tabulations, it's not clear yet how to find subclonal variants since the workflow that I found to be optimal requires both strands of nucleic acid. However, if you look at Figure 4 of the mtscATAC-seq paper, we do indeed analyze 5' scRNAseq data as part of the CLL analyses.
