### ISSUE TITLE
multiple samples

### ISSUE THREAD

**Issue by chrismahony** [caleblareau/mgatk#55]
I have 13 samples and I have ran mgatk tenx to call variants in each separate sample in the mt genome.

After I read in the separate MGATK data in R using ReadMGATK(), how can I combine these and add this to my aggregated seurat object (that contains all 13 samples)? (whilst retaining metadata about each samples identity) 

Thanks
Chris

**Comment by caleblareau** [comment]
so the output of the function is a list of sparse matrix counts and a dataframe of meta data. 

I haven't done this myself yet, but what should work is if you `cbind()` the counts matrix and `rbind()`

Note: the key assumptions of mgatk will work only for cells from the same donor; otherwise, you're going to identify mostly polymorphisms distinct from the different donors.
