### ISSUE TITLE
multiple bam files with call mode

### ISSUE THREAD

**Issue by rtyags** [caleblareau/mgatk#57]
Hi Caleb,

I tried running call mode with outputs from multiple 10x runs. I assumed this would end up with similar output files as the individual runs with tenx mode.

So, I expected something like : 

```
arc_mgatk.A.txt.gz                      arc_mgatk.C.txt.gz        arc_mgatk.rds         arc_mgatk.variant_stats.tsv.gz
arc_mgatk.cell_heteroplasmic_df.tsv.gz  arc_mgatk.depthTable.txt  arc_mgatk.signac.rds  arc_mgatk.vmr_strand_plot.png
arc_mgatk.coverage.txt.gz               arc_mgatk.G.txt.gz        arc_mgatk.T.txt.gz    chrM_refAllele.txt
```

but I only see : 

```
arc_mgatk.A.txt.gz         arc_mgatk.C.txt.gz        arc_mgatk.G.txt.gz  arc_mgatk.signac.rds  chrM_refAllele.txt
arc_mgatk.coverage.txt.gz  arc_mgatk.depthTable.txt  arc_mgatk.rds       arc_mgatk.T.txt.gz
```

Am I right in assuming that call mode should also result in similar output? If so, do you know what might have gone wrong in this case?

Thanks

**Comment by caleblareau** [comment]
In short, we only produce the extra files from `tenx` mode, simply because there are assumptions about the variant calling applicable to that mode rather than the more general cases that `call` handles; So it’s producing the right outputs. If you used call, you probably treated each sample like a pseudobulk, which may not be the desired behavior ?

On May 2, 2022, at 3:57 PM, rtyags ***@***.******@***.***>> wrote:



Hi Caleb,

I tried running call mode with outputs from multiple 10x runs. I assumed this would end up with similar output files as the individual runs with tenx mode.

So, I expected something like :

arc_mgatk.A.txt.gz                      arc_mgatk.C.txt.gz        arc_mgatk.rds         arc_mgatk.variant_stats.tsv.gz
arc_mgatk.cell_heteroplasmic_df.tsv.gz  arc_mgatk.depthTable.txt  arc_mgatk.signac.rds  arc_mgatk.vmr_strand_plot.png
arc_mgatk.coverage.txt.gz               arc_mgatk.G.txt.gz        arc_mgatk.T.txt.gz    chrM_refAllele.txt


but I only see :

arc_mgatk.A.txt.gz         arc_mgatk.C.txt.gz        arc_mgatk.G.txt.gz  arc_mgatk.signac.rds  chrM_refAllele.txt
arc_mgatk.coverage.txt.gz  arc_mgatk.depthTable.txt  arc_mgatk.rds       arc_mgatk.T.txt.gz


Am I right in assuming that call mode should also result in similar output? If so, do you know what might have gone wrong in this case?

Thanks
