### ISSUE TITLE
No heteroplasmic mutations

### ISSUE THREAD

**Issue by VittoriaDBocchi** [caleblareau/mgatk#71]
Hi! Thank you so much for developing this great tool!
I got the pipeline running however when I look at the vmr_strand_plot I see that there is no heteroplasmy. The data derives from ES cells differentiated into neurons and I have different stages of differentiation (including pluripotency) so I was not expecting this output. Could this be due to low coverage on the ATAC data (this data was produced using the 10x Multiome kit)? Do you have any suggestions on why this could be?
Thank you so much for your help!
Vittoria
![Test2 vmr_strand_plot](https://github.com/caleblareau/mgatk/assets/120423622/d83c64ae-5eaa-43eb-9e49-557c809b7ef5)

**Comment by caleblareau** [comment]
Hi @VittoriaDBocchi 

Basically for the internal variant calling function, we only include cells with at least 10 mean mtDNA coverage. If you are using the standard multiome kit (ie without LLL and fixation), you'll get very very low mtDNA yields probably few, if any cells, made it into this analysis, which is why you don't see anything. 

In our experience, the standard multiome kit does cause mitos to associate with different nuclei, so what little data is there is not really good either unless you do a fixation step as we described here: https://www.nature.com/articles/s41587-021-00927-2

**Comment by VittoriaDBocchi** [comment]
Thank you so much for your help and suggestion. We did follow the fixation step and I think the problems is the sequencing depth. We have 22,000 reads/cell but looking at the mitochondrial coverage we are well below what you describe in your protocol.
I think we need to sequence much deeper...
Thank you again for your help.
Vittoria
<img width="318" alt="coverage" src="https://github.com/caleblareau/mgatk/assets/120423622/668a36a0-f62c-4231-90e8-d7aa810db459">
