### ISSUE TITLE
getBarcode in chunk_barcoded_bam.py always returns barcode (and not umi) 

### ISSUE THREAD

**Issue by yaniv-el** [caleblareau/mgatk#75]
Hi,

If I understand the flow correctly, I think that the latest commit introduced a bug into chunk_barcoded_bam.py. 
The function getBarcode always returns the barcode_id tag even when asked for the umi_id one. 
This can easily be fixed by letting it return `read.get_tag(tag_get)`

Best,
Yaniv

**Comment by caleblareau** [comment]
thanks for bringing this up-- I will push a new version tonight

**Comment by caleblareau** [comment]
Hi @yaniv-el, maybe I misunderstand your point-- I think the version is OK?

https://github.com/caleblareau/mgatk/commit/892daa1044c347ad4bd35057dc782da0359ea3c9

Since the `get_tag` function call is still parameterized by the sam tag (i.e. `tag_get`), then it would correctly return either the cell barcode or the UMI depending on when the function is called-- do you think otherwise?

**Comment by yaniv-el** [comment]
Hi,

In the version I have the line in the getBarcode function is:
`return read.get_tag(barcodeTag, tag_get)[0]`
Which ignores the tag_get parameter and always returns the barcode tag.
Fixing it to:
`return read.get_tag(tag_get)[0]`
Seems to return the desired tag (barcode/umi).

Yaniv

**Comment by caleblareau** [comment]
Ah— got it; thanks for clarifying. Will update

On Jul 17, 2023, at 1:37 AM, yaniv-el ***@***.***> wrote:

﻿

Hi,

In the version I have the line in the getBarcode function is:
return read.get_tag(barcodeTag, tag_get)[0]
Which ignores the tag_get parameter and always returns the barcode tag.
Fixing it to:
return read.get_tag(tag_get)[0]
Seems to return the desired tag (barcode/umi).

Yaniv

**Comment by caleblareau** [comment]
pushed v.0.6.9-- thank you for your edit @yaniv-el
